---
title: "Lecture 04 - Exercise solutions"
format:
  html:
    toc: true
    toc-depth: 3
    embed-resources: true
execute:
  echo: true
  warning: true
engine: knitr
---

```{r setup}
#| include: false
options(width = 80)
```

<!-- 
Make sure you have numpy installed
! uv sync # or
! uv add numpy
-->

```{python py_setup}
#| echo: false
import numpy as np
```


# Exercise 1

Without running the code, determine the result (or error) of each expression.

## R

```{r}
x = c(a = 2, b = 4, c = 6, d = 8)

x[c(1, 3)]          # c(a=2, c=6)
x[-c(1, 3)]         # c(b=4, d=8)
x[c(TRUE, FALSE)]   # c(a=2, c=6)
x[c("d", "b", "z")] # c(d=8, b=4, z=NA)
x[x > 3 & x < 8]    # c(b=4, c=6)
```

## Python / NumPy

```{python}
#| eval: false
x = np.array([2, 4, 6, 8])

x[[0, 2]]                    # np.array([2, 6])
x[-2:]                       # np.array([6, 8])
x[np.array([True, False])]   # Error - not length 4
x[x > 3 & x < 8]             # Error - not enough ()
x[(x > 3) & (x < 8)]         # np.array([4,6])
```

# Exercise 2

